import type { Character } from "@/store/character-store";

export const MOCK_CHARACTERS: Character[] = [
  {
    id: "1",
    name: "Sakura",
    slug: "sakura",
    description: "Милая и заботливая подруга из академии",
    greeting_message: "Привет! Рада тебя видеть~",
    avatar_url: null,
    preview_url: "https://picsum.photos/seed/sakura/400/520",
    tags: ["аниме", "романтика"],
    category: "general",
    message_price: 1,
    generation_price: 10,
    is_nsfw: false,
    sort_order: 0,
  },
  {
    id: "2",
    name: "Luna",
    slug: "luna",
    description: "Загадочная лунная принцесса",
    greeting_message: "Ночь прекрасна, не правда ли?",
    avatar_url: null,
    preview_url: "https://picsum.photos/seed/luna/400/520",
    tags: ["фэнтези", "милая"],
    category: "general",
    message_price: 1,
    generation_price: 10,
    is_nsfw: false,
    sort_order: 1,
  },
  {
    id: "3",
    name: "Mika",
    slug: "mika",
    description: "Энергичная спортсменка с характером",
    greeting_message: "Эй! Погнали тренироваться!",
    avatar_url: null,
    preview_url: "https://picsum.photos/seed/mika/400/520",
    tags: ["спорт", "активная"],
    category: "general",
    message_price: 1,
    generation_price: 10,
    is_nsfw: false,
    sort_order: 2,
  },
  {
    id: "4",
    name: "Yuki",
    slug: "yuki",
    description: "Тихая библиотекарша с тайной",
    greeting_message: "Шhh... хочешь услышать историю?",
    avatar_url: null,
    preview_url: "https://picsum.photos/seed/yuki/400/520",
    tags: ["спокойная", "интеллект"],
    category: "general",
    message_price: 1,
    generation_price: 10,
    is_nsfw: false,
    sort_order: 3,
  },
];
